version: "3.1"

services:
  jarvey-streams:
    image: kwlee0220/jarvey.streams:0.1.0
    container_name: jarvey-streams
    network_mode: host
    environment:
      KAFKA_APPLICATION_ID_CONFIG: "node-track"
#      KAFKA_BOOTSTRAP_SERVERS_CONFIG: "kafka01:9092,kafka02:9092,kafka03:9092"
      KAFKA_BOOTSTRAP_SERVERS_CONFIG: "localhost:9091,localhost:9092,localhost:9093"
      
      DNA_TOPIC_TRACKS: "node-tracks"
      DNA_TOPIC_ZONE_LINE_RELATIONS: "zone-line-relations"
      DNA_TOPIC_ZONE_LOCATIONS: "zone-locations"
      DNA_TOPIC_ZONE_RESIDENTS: "zone-residents"
      DNA_TOPIC_LOCATION_EVENTS: "location-events"
      
      DNA_JDBC_URL: "jdbc:postgresql://host.docker.internal:5432/dna"
      DNA_JDBC_USER: "dna"
      DNA_JDBC_PASSWORD: "urc2004"

  turn-detect:
    image: kwlee0220/jarvey.streams.turn:0.1.0
    container_name: turn-detect
    network_mode: host
    environment:
      KAFKA_APPLICATION_ID_CONFIG: "turn-detect"
      KAFKA_BOOTSTRAP_SERVERS_CONFIG: "localhost:9091,localhost:9092,localhost:9093"

      DNA_TOPIC_LOCATION_EVENTS: "location-events"
      DNA_TOPIC_TURN_EVENTS: "turn-events"
    depends_on:
      - jarvey-streams